name: datascience
channels:
- defaults
- conda-forge
dependencies:
- awscli
- beautifulsoup4
- botocore
- boto
- boto3
- bqplot
- click
- cloudpickle
- cython
- dask
- feather-format
- glmnet
- h2o
- ipython
- ipywidgets
- jinja2
- joblib
- jsonschema
- jupyter
- libffi
- libgfortran
- libtiff
- libxml2
- matplotlib
- nomkl
- notebook
- nose
- numexpr
- numpy
- openblas
- pandas
- patsy
- pip
- psycopg2
- pyarrow
- pycrypto
- pytest
- python=3.7.6
- pyyaml
- requests
- s3fs
- seaborn
- scipy
- scikit-learn
- statsmodels
- urllib3
- xgboost
- pip:
  - civis
  - civisml-extensions
  - dropbox
  - ftputil
  - muffnn
  - pubnub
  - pysftp
  - requests-toolbelt
  - tensorflow