name: datascience
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _py-xgboost-mutex=2.0
  - argon2-cffi=20.1.0
  - arrow-cpp=0.15.1
  - async_generator=1.10
  - attrs=20.3.0
  - awscli=1.18.199
  - backcall=0.2.0
  - beautifulsoup4=4.9.3
  - blas=1.0
  - bleach=3.2.1
  - bokeh=2.2.3
  - boost-cpp=1.71.0
  - boto=2.49.0
  - boto3=1.16.39
  - botocore=1.19.39
  - bqplot=0.12.18
  - brotli=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2020.12.8
  - certifi=2020.12.5
  - cffi=1.14.0
  - chardet=4.0.0
  - click=7.1.2
  - cloudpickle=1.6.0
  - colorama=0.4.3
  - cryptography=3.3.1
  - cycler=0.10.0
  - cython=0.29.21
  - cytoolz=0.11.0
  - dask=2020.12.0
  - dask-core=2020.12.0
  - dbus=1.13.18
  - decorator=4.4.2
  - defusedxml=0.6.0
  - distributed=2020.12.0
  - docutils=0.15.2
  - double-conversion=3.1.5
  - entrypoints=0.3
  - expat=2.2.10
  - feather-format=0.4.1
  - fontconfig=2.13.0
  - freetype=2.10.4
  - fsspec=0.8.3
  - gflags=2.2.2
  - glib=2.63.1
  - glmnet=2.2.1
  - glog=0.4.0
  - grpc-cpp=1.26.0
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h2o=3.18.0.2
  - heapdict=1.0.1
  - icu=58.2
  - idna=2.10
  - importlib-metadata=2.0.0
  - importlib_metadata=2.0.0
  - iniconfig=1.1.1
  - ipykernel=5.3.4
  - ipython=7.19.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.17.2
  - jinja2=2.11.2
  - jmespath=0.10.0
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.7
  - jupyter_console=6.2.0
  - jupyter_core=4.7.0
  - jupyterlab_pygments=0.1.2
  - kiwisolver=1.3.0
  - krb5=1.16.4
  - lcms2=2.11
  - ld_impl_linux-64=2.33.1
  - libboost=1.71.0
  - libedit=3.1.20191231
  - libevent=2.1.8
  - libffi=3.2.1
  - libgcc-ng=9.3.0
  - libgfortran=3.0.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=9.3.0
  - libopenblas=0.3.10
  - libpng=1.6.37
  - libpq=11.2
  - libprotobuf=3.11.2
  - libsodium=1.0.18
  - libstdcxx-ng=9.3.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libxcb=1.14
  - libxgboost=1.3.0
  - libxml2=2.9.10
  - locket=0.2.0
  - lz4-c=1.8.1.2
  - markupsafe=1.1.1
  - matplotlib=3.3.2
  - matplotlib-base=3.3.2
  - mistune=0.8.4
  - more-itertools=8.6.0
  - msgpack-python=1.0.1
  - nbclient=0.5.1
  - nbconvert=6.0.7
  - nbformat=5.0.8
  - ncurses=6.2
  - nest-asyncio=1.4.3
  - nomkl=3.0
  - nose=1.3.7
  - notebook=6.1.5
  - numexpr=2.7.1
  - olefile=0.46
  - openblas=0.3.10
  - openblas-devel=0.3.10
  - openjdk=8.0.152
  - openssl=1.1.1i
  - packaging=20.8
  - pandas=1.1.5
  - pandoc=2.11
  - pandocfilters=1.4.3
  - parso=0.7.0
  - partd=1.1.0
  - patsy=0.5.1
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.0.1
  - pip=20.3.3
  - pluggy=0.13.1
  - prometheus_client=0.9.0
  - prompt-toolkit=3.0.8
  - prompt_toolkit=3.0.8
  - psutil=5.7.2
  - psycopg2=2.8.4
  - ptyprocess=0.6.0
  - py=1.10.0
  - py-xgboost=1.3.0
  - pyarrow=0.15.1
  - pyasn1=0.4.8
  - pycparser=2.20
  - pycrypto=2.6.1
  - pygments=2.7.3
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - pytest=6.2.1
  - python=3.7.6
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytz=2020.4
  - pyyaml=5.3.1
  - pyzmq=20.0.0
  - qt=5.9.7
  - qtconsole=4.7.7
  - qtpy=1.9.0
  - re2=2020.11.01
  - readline=7.0
  - requests=2.25.1
  - rsa=4.0
  - s3fs=0.4.2
  - s3transfer=0.3.3
  - scipy=1.5.2
  - seaborn=0.11.0
  - send2trash=1.5.0
  - setuptools=51.0.0
  - sip=4.19.8
  - six=1.15.0
  - snappy=1.1.8
  - sortedcontainers=2.3.0
  - soupsieve=2.1
  - sqlite=3.33.0
  - statsmodels=0.12.1
  - tblib=1.7.0
  - terminado=0.9.1
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - thrift-cpp=0.11.0
  - tk=8.6.10
  - toml=0.10.1
  - toolz=0.11.1
  - tornado=6.1
  - traitlets=4.3.3
  - traittypes=0.2.1
  - typing_extensions=3.7.4.3
  - uriparser=0.9.3
  - urllib3=1.25.11
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.2
  - widgetsnbextension=3.5.1
  - xgboost=1.3.0
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.3
  - zict=2.0.0
  - zipp=3.4.0
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - absl-py==0.11.0
    - arrow==0.17.0
    - astor==0.8.1
    - bcrypt==3.2.0
    - binaryornot==0.4.4
    - cached-property==1.5.2
    - cbor2==5.2.0
    - civis==1.15.1
    - civisml-extensions==0.3.0
    - cookiecutter==1.7.2
    - dropbox==11.0.0
    - ftputil==4.0.0
    - gast==0.2.2
    - google-pasta==0.2.0
    - grpcio==1.34.0
    - h5py==3.1.0
    - jinja2-time==0.2.0
    - joblib==0.14.1
    - jsonref==0.2
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - markdown==3.3.3
    - muffnn==2.3.2
    - numpy==1.18.5
    - opt-einsum==3.3.0
    - paramiko==2.7.2
    - ply==3.11
    - poyo==0.5.0
    - protobuf==3.14.0
    - pubnub==4.8.0
    - pycryptodomex==3.9.9
    - pynacl==1.4.0
    - pysftp==0.2.9
    - python-slugify==4.0.1
    - requests-toolbelt==0.9.1
    - scikit-learn==0.22.2.post1
    - stone==3.2.1
    - tenacity==6.3.1
    - tensorboard==1.15.0
    - tensorflow==1.15.4
    - tensorflow-estimator==1.15.1
    - termcolor==1.1.0
    - text-unidecode==1.3
    - werkzeug==1.0.1
    - wrapt==1.12.1
